### ISSUE TITLE
clEnqueueNDRangeKernel failed: OUT_OF_RESOURCES 

### ISSUE THREAD

**Issue by MrGouYou** [axeldavy/vnlnet#2]
hi,,i get this bug when i  am tesing
python3 test.py directory --net vnlnet_color_20.pth --input data/videos/ --output data/output/

![image](https://user-images.githubusercontent.com/12627651/60950589-076c4200-a32a-11e9-9d50-e0b01f226f85.png)

**Comment by axeldavy** [comment]
Thanks for the bug report, I will investigate.
Could you indicate:
. Hardware configuration
. length of the video and size of the frames

**Comment by axeldavy** [comment]
I managed to reproduce the issue with the Intel OpenCL CPU official driver.
A quick workaround if you want to use CPU opencl is to use POCL.

I will investigate how to make the code run for the Intel OpenCL CPU driver.

**Comment by axeldavy** [comment]
I figured out the CPU driver doesn't like a small optimization designed for GPU. (Basically we use a local cache, and the driver finds that cache too big).

I've prepared a patch that disables the optimization when detecting a CPU. Please reopen the issue if the bug isn't fixed on your side.

That said, running with a CPU driver takes a really long time. I would recommand if you can to run the code on a gpu.
