### ISSUE TITLE
Hi，There is sometimes a mistake when I trained the network.

### ISSUE THREAD

**Issue by Abnerminjian** [axeldavy/vnlnet#3]
When I trained the  neural network ，there is sometimes a error.Sometimes the network was trained in the 18th or 16th even 3th epoch,the error will happen.I think whether my data size is not enough,because I used my own dataset.My datasets consists of around 729 extracts with 16 frames which is smaller yours.Of course,I just used your script to  generate my datasets so I doubt that whether the quantity of my datasets is not enough so that the error happened.

![1563501783(1)](https://user-images.githubusercontent.com/43443967/61504212-27c48c80-aa0d-11e9-8d1e-9855ce69fac4.png)

**Comment by axeldavy** [comment]
Hi,

As you can see here,
https://github.com/axeldavy/vnlnet/blob/master/dataset.py#L99

If a given subdirname (between '01' and '09') doesn't exist, the video is skipped.
Your error message seems to indicate self.keys is empty. Possibly the previous loop skipped all videos it looked at. That would happen if many of your videos are missing subdirectories.

While our dataset was big enough to consider only training on a small fraction every epoch, you could try  to train on a bigger fraction (or even the whole dataset).
If you want to train on your entire dataset, you can consider changing:
https://github.com/axeldavy/vnlnet/blob/master/dataset.py#L97
by removing the '[:3]' which selects only a few videos of the category.
You can also choose to iterate over subdirnames to take all the ones available.

**Comment by RenieWell** [comment]
I met the same problem, and I met many problem in compiling the https://github.com/cmla/f16-video-set project, for that I worked in Windows system.
Can you share the structure of the train dataset, so I can make my own dataset.

**Comment by pariasm** [comment]
The structure is the following:

`dataset-root/category/video-id/segment-number/frame-number.png`

where

- `data` is the root folder of the dataset
- `category` is the keyword that we searched in Youtube, e.g. ants, violin, cars, etc.
- `video-id` is the hash in the youtube URL identifying the video. For instance if the URL is `https://www.youtube.com/watch?v=0ytoUuO-qvg` then `0ytoUuO-qvg` is the video-id.
- `segment-number` is a two-digit number identifying the 16 frames video segment (several 16 frames video segments are extracted from each video)
- `frame-number` is the three-digit frame number.


For example:

```
dataset/
├── antelope/
│   ├── 1-3nsKBaDno/
│   │   ├── 00/
│   │   │   ├── 001.png 
│   │   │   ├── 002.png 
│   │   │   ├── ...
│   │   │   ├── 015.png
│   │   │   └── 016.png
│   │   ├── 01/
│   │   │   ├── 001.png
│   │   │   ├── ...
│   │   ├── ...
│   ├──  31HKCYxobXs/
│   │   ├── 00/
│   │   │   ├── 001.png 
│   │   │   ├── ...
│   │   ├── ...
│   │   ...
│   ...
├── ants/
│   ├── 0seLd3NJ1cA/
...
```

**Comment by RenieWell** [comment]
It is quite clear, thanks a lot for your help!
